### ISSUE TITLE
Ver error en dev

### ISSUE THREAD

**Issue by germankay** [unckan/ckan-env#37]
Logs de error:
```


PUSH_ERROR *https://localhost:5000*
v0.1.4 - CKAN 2.10.5
2024-12-04T18:21:32.870260 user: ckan_admin
INTERNAL_ERROR [Errno -3] Temporary failure in name resolution [(ConnectError)]
    TRACE
```nc/connection.py", line 101, in handle_request
    raise exc
  File "/app/unckan/venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 78, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 207, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/app/unckan/venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/unckan/venv/lib/python3.11/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/flask_debugtoolbar/__init__.py", line 142, in dispatch_request
    return view_func(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/ckanext/superset/decorators.py", line 16, in view_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/ckanext/superset/blueprints/superset.py", line 27, in index
    sc.load_charts()
  File "/app/unckan/venv/lib/python3.11/site-packages/ckanext/superset/data/main.py", line 77, in load_charts
    self.charts_response = self.get("chart/", params=params)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/ckanext/superset/data/main.py", line 174, in get
    self.prepare_connection()
  File "/app/unckan/venv/lib/python3.11/site-packages/ckanext/superset/data/main.py", line 143, in prepare_connection
    login_response = [self.client.post](http://self.client.post/)(login_url, json=self.login_payload)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/httpx/_client.py", line 1157, in post
    return self.request(
           ^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/httpx/_client.py", line 837, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
```

**Comment by avdata99** [comment]
La propiedad `client` del objeto `SupersetCKAN` definido en `data/main.py` es del tipo `httpx.Client` y se conecta a servicios que no dependen de nosotros

Todos las llamadas a `client.get` y `client.post` deben capturar errores
Bajar el código de la librería `httpx` y ver que errores podrían lanzarse.
Capturar estos posibles y gestionar el error de forma de que el usuario final sepa que hubo un error al conectarse con la instancia de superset con información general en el mensaje de error al público pero con un error mas detallado en el log interno.
Internamente usar `log.critical` para que este error sea expuesto por la extension `push-errors` si esta estubiera en uso.

**Comment by avdata99** [comment]
No parece un error real. Version vieja
